import React, { useEffect, useState } from 'react'

import { login } from '../actions/authActions';
import { clearErrors } from '../actions/errorActions';
import { useDispatch, useSelector } from 'react-redux';

import { Redirect, useNavigate, Link } from 'react-router-dom';

import Header from "../components/header";
import Footer from "../components/footer";

const Login = () => {

    const [user, setUser] = useState({   
        email: "",
        password: "",
    })

    const [invalidErr, setInvalidErr] = useState(null)
    const [emailErr, setEmailErr] = useState(null)
    const [passwordErr, setPasswordErr] = useState(null)

    const auth = useSelector(state => state.auth)
    const { userSuccessMsg, isAuthenticated } = auth

    const error = useSelector(state => state.error)

    const dispatch = useDispatch()

    //checking errors
    useEffect(() => {
        if(error.id === 'LOGIN_FAIL'){
            setInvalidErr(error.msg.errors.invalid && error.msg.errors.invalid[0])
            setEmailErr(error.msg.errors.email && error.msg.errors.email[0])
            setPasswordErr(error.msg.errors.password && error.msg.errors.password[0])
        }
    }, [error])

    const onSubmit = (e) => {
        e.preventDefault();

        dispatch(login(user));

        setUser({
            email: "",
            password: "",
        })

        setInvalidErr(null)
        setEmailErr(null)
        setPasswordErr(null)

        //clears generated by redux
        dispatch(clearErrors())
    }

    const navigate = useNavigate();

    if(isAuthenticated) return navigate("/");

    return (
        <>
          <Header homepage="false" />
        {/* contact */}
        <section className="contact section-padding" data-scroll-index="5">
            <div className="container">
                <div className="row">
    
                    <div className="section-head text-center col-sm-12">
                    { invalidErr && <p className="alert alert-danger text-center">{invalidErr}</p> }
                        <h4>Login</h4>
                        <h6>Stay In Touch</h6>
                    </div>
                    
                    {/* <!-- Contact Form --> */}
                    <div className="col-md-12">
                        <form className="form" id="contact-form" onSubmit={onSubmit}>
    
                            <div className="messages"></div>
    
                            <div className="controls">
    
                                <div className="row">
    
                                    <div className="col-md-6">
                                        <div className="form-group">
                                            <input id="form_email" type="email" name="email" placeholder="Email *" required="required"
                                            data-error="Email is required."
                                            value={user.email}
                                            onChange={(e) => setUser({...user, email:e.target.value})}
                                            />
                                            { emailErr && <div className="help-block with-errors text-danger">{emailErr}</div> }
                                        </div>
                                    </div>

                                    <div className="col-md-6">
                                        <div className="form-group">
                                            <input id="form_password" type="password" name="password" placeholder="Password *" required="required"
                                            data-error="Valid email is required."
                                            value={user.password}
                                            onChange={(e) => setUser({...user, password:e.target.value})}
                                            />
                                            { passwordErr && <div className="help-block with-errors text-danger">{passwordErr}</div> }
                                        </div>
                                    </div>
                                    
    
                                    <div className="col-md-12">
                                        <button type="submit" className="butn butn-bg"><span>Submit</span></button>
                                        <div className="info">
                                            <span><strong>Forgot Password?</strong> : Click Here</span>
                                            <span><strong>OR</strong> Click <Link to="/register" className="bg-dark p-2 text-white">Register</Link> to Sign-Up</span>
                                            
                                        </div>
                                    </div>
    
                                </div>                             
                            </div>
                        </form>
                    </div>
    
                </div>
            </div>
        </section>
    
    
    
          <Footer />
        </>
      );
}

export default Login